name: crawl
on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  crawl:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run code
        run: go run ./*.go crawl

      - name: Push dist to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist